[toolchain]
# version is needed since nightly versions don't always have every component
channel = "nightly-2023-05-02"
components = ["rustfmt", "rust-src", "llvm-tools-preview", "bootimage"]
targets = ["x86_64-unknown-none"]