name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  TOOLCHAIN: nightly

jobs:
  ci:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: Windows
            os: windows-latest
          - identifier: Ubuntu
            os: ubuntu-latest
          - identifier: MacOS
            os: macos-latest

    name: CI - ${{ matrix.identifier }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: update rust
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2
      - name: build
        run: cargo build --verbose
      - name: check formatting
        run: cargo fmt --all -- --check